### ISSUE TITLE
Owner is no admin (adminbar missing)

### ISSUE THREAD

**Issue by CvH** [CADLAB-io/CADLAB.io-swarm-stack#2]
After installation the first user is automatically promoted to owner.
But it looks like that the owner has no full admin rights or something in between so the admin bar at the top is missing after login.
![image](https://user-images.githubusercontent.com/1355173/187598327-cdb466ee-d97c-415f-964b-82e75dee83e7.png)

Adding a user still works, but no way to configure anything.
Workaround: add a user, login into the mysql docker -> add the admin flag to the users_group DB table for the added user.
For the plain admin user it works like intended.

**Comment by CvH** [comment]
Additional I can't edit the users roles.

`http://my.domain/user/3/edit?destination=admin/people`

![image](https://user-images.githubusercontent.com/1355173/187602334-f53e2d1d-8dc7-4eea-87c8-d038cb2678b8.png)

**Comment by dzhgenti** [comment]
Please get in touch with the support at info@cadlab.io. We don't use GitHub issues for handling support queries.

Thank you
